### ISSUE TITLE
感觉词库很小啊。成语什么的都没有

### ISSUE THREAD

**Issue by tzws** [ZSaberLv0/ZFVimIM#1]
自己一个字一个字的去拼一个成语，速度很慢，还容易出错。

**Comment by ZSaberLv0** [comment]
词库是我个人在用的, 因为之前找了很多大而全的词库其实有很多废词组, 洁癖患者忍不了, 数据量很大又没有很好的方式删, 所以初始词库只保留 2 个字以下的

另外, 没有 python 的情况下, 纯 vim 脚本加载词库比较慢 (而且无法异步), 之前测过某个 4M 左右的词库大约得 5~10 秒, 得不偿失

如果觉得词库不全, 可以自己找各种大词库 (比如X狗的词库), 然后按照格式处理一下就行

**Comment by ZSaberLv0** [comment]
https://github.com/ZSaberLv0/ZFVimIM_pinyin_huge

@tzws 加了个比较全的词库, 顺便优化了下对大词库读写的内存消耗, 有兴趣可以更新下插件再换成这个词库试试 (不过估计读取时间依旧感人)
