### ISSUE TITLE
Split DB files to multiple files based on the first character

### ISSUE THREAD

**Issue by suliveevil** [ZSaberLv0/ZFVimIM#10]
Would that make ZFVimIM faster by loading db files as needed?

**Comment by ZSaberLv0** [comment]
* if you have no python or job, load by pure vim script always takes very long time, but since async mode is not available, it only load and push one time when you enter and leave, for this case, split db does not reduce loading time
* if you have python and job, the main performance issue locates in `passing huge Dictionary data from python to vim`, which should be acceptable lag (about 50~800ms accorrding to your db size), for this case, split db make things much more complex and has little benefit (one `800ms` lag is a pain, but `26 x 40ms` randomly lag is also a pain)

the only way to completely solve performance issue, is to put all logic and all db data to python side, but as described in FAQ, this is not the main purpose of this plugin

so, try to make your python and job available, otherwise, use tiny db just as a fallback solution

**Comment by suliveevil** [comment]
Do I have to install https://github.com/ZSaberLv0/ZFVimJob?
My iVim have job and python3

```viml

ver
------
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2020 16:26:10)
iVim 2.22(3)
Included patches: 1-2110
Modified by Boogaloo
Huge version with iOS GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       -tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        -terminfo
-balloon_eval      -footer            -mzscheme          -termresponse
-balloon_eval_term +fork()            -netbeans_intg     +textobjects
+browse            -gettext           -num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       -iconv             +path_extra        +title
+channel           +insert_expand     -perl              -toolbar
+cindent           +job               +persistent_undo   +user_commands
-clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      -libcall           +python3/dyn       +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
-cscope            +localmap          -ruby              +wildmenu
+cursorbind        +lua/dyn           +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       -X11
+diff              +modify_fname      -sound             -xfontset
+digraphs          +mouse             +spell             -xim
-dnd               -mouseshape        +startuptime       -xpm
-ebcdic            +mouse_dec         +statusline        -xsmp
+emacs_tags        -mouse_gpm         -sun_workshop      -xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"


```

**Comment by suliveevil** [comment]
The pinyin_huge is really make changing to insert-pinyin mode slow.
I combined your pinyin and wubi, it's a little faster than pinyin_huge.

**Comment by ZSaberLv0** [comment]
yes, python and ZFVimJob is required to improve performance, and you may use `ZFVimIM_cloudAsyncAvailable()` to check whether it works

**Comment by suliveevil** [comment]
It's 0.
Why this `cloudSync` affects the local ?

**Comment by ZSaberLv0** [comment]
async mode's internal check is: `executable('git') && exists('*ZFJobAvailable') && ZFJobAvailable()`

the default ZFJob impl depends on either of:
* vim8's job: `exists('*job_start') && has('channel') && has('patch-7.4.1590')`
* nvim: `exists('*jobstart')`

`has('python')` or `has('python3')` is not necessary for async mode but recommended

**Comment by suliveevil** [comment]
I just want use local db file (because I have no other choice).
Does this means I don't have to install ZFVimJob?

**Comment by suliveevil** [comment]
If we can define which db file load before going into insert-pinyin mode,
which should load after, that will be a even nicer user experience.
Just like Plugin's LazyLoad.

For example, before we go into insert-pinyin mode,
ZFVimIM load pinyin_base db file, 
after startup ZFVimIM load other db files.


![dbload](https://user-images.githubusercontent.com/35763237/84735543-60326900-afd6-11ea-9eb1-20d3473740ec.png)

**Comment by ZSaberLv0** [comment]
> I just want use local db file (because I have no other choice).
> Does this means I don't have to install ZFVimJob?

yes, it's only required for async mode


> If we can define which db file load before going into insert-pinyin mode,
> which should load after, that will be a even nicer user experience.
> Just like Plugin's LazyLoad.
> 
> For example, before we go into insert-pinyin mode,
> ZFVimIM load pinyin_base db file,
> after startup ZFVimIM load other db files.

for lazy load, you may manually call these when desired:
1. `ZFVimIM_dbInit` to setup
1. `ZFVimIM_cloudRegister` or `ZFVimIM_dbLoad`, to perform actual load


PS: I now know your use case (have `python` and `job`, but no `git`), commit 72e5f79114199495979c5e92d4a1e339f1979f63 should make async mode work for you

**Comment by suliveevil** [comment]
Awesome! It makes mode switch fast as native!

**Comment by hao-lee** [comment]
一个中文输入法，你们俩用英文讨论问题...

**Comment by ZSaberLv0** [comment]
> 一个中文输入法，你们俩用英文讨论问题...

你也可以外挂日文词库, 就变成日文输入法啦 :P

**Comment by suliveevil** [comment]
> 一个中文输入法，你们俩用英文讨论问题...

方便懂英文不懂中文的人看。
