### ISSUE TITLE
关于词典库同步的问题

### ISSUE THREAD

**Issue by hao-lee** [ZSaberLv0/ZFVimIM#15]
如果我同时在多个机器上使用同一个GitHub仓库做词库，这多个本地仓库能保证互相之间的同步吗，会不会遇到merge冲突，插件会如何自动处理。

**Comment by ZSaberLv0** [comment]
`git fetch` > `git reset --hard origin/master` > apply diff > `git push`

所以一般情况下不会有什么问题

极端情况, 比如两个 vim 实例对同一个 local repo 进行操作, 且恰好一个在 apply diff 一个在 git 操作, 有可能丢失数据, 不过目前好像还没有遇到过
