### ISSUE TITLE
随着时间推移，插件的反应速度逐渐变慢

### ISSUE THREAD

**Issue by hao-lee** [ZSaberLv0/ZFVimIM#17]
vim刚打开时，打字飞快，大概使用10分钟左右，甚至不到，就明显感觉卡顿，下拉列表弹出变慢，空格上屏也卡，不知道为什么。重启vim就又可以了，然后又是一个轮回。

**Comment by ZSaberLv0** [comment]
出现卡顿之后, 提供一下这些信息:

* `let g:ZFVimIM_DEBUG_profile = 1` , 输入一些东西, 然后 `call ZFVimIM_DEBUG_profileInfo()`
* `IMCloudLog`
* `echo ZFGroupJobTaskMap()`
* `g:ZFVimIM_db`

    ```
    redir! log.txt
    silent echo g:ZFVimIM_db
    redir END
    ```

**Comment by hao-lee** [comment]
> * `let g:ZFVimIM_DEBUG_profile = 1` , 输入一些东西, 然后 `call ZFVimIM_DEBUG_profileInfo()`

没有什么现象发生啊，日志在哪存着

> * `IMCloudLog`

这也是在 command mode 里输入吗

> * `echo ZFGroupJobTaskMap()`

我在内网，没开同步，Job插件被我禁了。

> * `g:ZFVimIM_db`
>   ```
>   redir! log.txt
>   silent echo g:ZFVimIM_db
>   redir END
>   ```

这段没看懂...

**Comment by ZSaberLv0** [comment]
好吧, 加了点方便取日志的东西, 你更新一下, 然后:

1. `call ZFVimIM_DEBUG_start('日志文件路径')`
1. 随便输入点什么, 等几秒
1. `call ZFVimIM_DEBUG_stop()`
1. 把日志文件传上来

---

另外, `ZFVimJob` 可以明显提升加载性能, 建议启用, 内网传不了 git 的话, 词库可以设置成本地模式:

```
call ZFVimIM_cloudRegister({
            \   'mode' : 'local',
            \   'dbId' : db['dbId'],
            \   'repoPath' : '/path/to/repo',
            \   'dbFile' : '/YourDbFile',
            \   'dbCountFile' : '/YourDbCountFile',
            \ })
```

**Comment by hao-lee** [comment]
输入的内容为 `因为测试结果表明, 很多指针的低位被位运算改变了需要特殊处理`

[log.txt](https://github.com/ZSaberLv0/ZFVimIM/files/5011778/log.txt)

**Comment by ZSaberLv0** [comment]
本地保存的词库修改没清一直重复在更新词库 `_(:з」∠)_` 已修复

**Comment by hao-lee** [comment]
大兄弟效率
