### ISSUE TITLE
希望加入中文说明文档

### ISSUE THREAD

**Issue by krisfans** [ZSaberLv0/ZFVimIM#19]
既然是中文输入法，能否考虑加入中文说明文档？

**Comment by ZSaberLv0** [comment]
有空看看，主要是懒
另外，都是基于词库的输入法，啥语言都行，不只是中文输入法

**Comment by ZSaberLv0** [comment]
https://github.com/ZSaberLv0/ZFVimIM/blob/master/README.CN.md

已添加
