### ISSUE TITLE
没用过此类插件，请问

### ISSUE THREAD

**Issue by BSDxxxx** [ZSaberLv0/ZFVimIM#2]
和vimim有什么区别？
没有词库是不是什么都输入不了？
搜索的时候可以实现用拼音搜索中文吗？

**Comment by ZSaberLv0** [comment]
* 和vimim有什么区别？
    * 可以快速组用户词
    * 可以长句输入
    * 可以后台自动同步词库
    * 纯文本词库加载性能更好 (用 python 异步加载)
    * 为了省事, 去掉了:
        * 第三方api实现的在线输入法 (实际体验并不好, 而且 `lmap` 本身没有异步功能, 网稍慢就卡)
        * bsddb 词库 (制作和修改都麻烦, 有 python 异步没啥必要)
* 没有词库是不是什么都输入不了？
    * 是, vimim 也是需要词库的
* 搜索的时候可以实现用拼音搜索中文吗？
    * 没有 vimim 那种直接在 command 输英文就能搜索的, 因为组词问题, 体验并不好 (你没法知道你输的英文对应的是什么词组)
    * 可以 `q:` 或 `q/` 在 `command-line window` 里面输中文
