### ISSUE TITLE
在低版本的vim里不显示输入法

### ISSUE THREAD

**Issue by leoatchina** [ZSaberLv0/ZFVimIM#21]
还是wsl, centos7里带的vim，我装了五笔和拼音，然后按`;:`, 实际是切换过去了，正常打字，但是下面没变， 都是`(lang)`
![image](https://user-images.githubusercontent.com/4470821/109089230-dc777180-774b-11eb-9711-156f7b7e2317.png)

![image](https://user-images.githubusercontent.com/4470821/109089186-c964a180-774b-11eb-8bf3-bfd025523441.png)

**Comment by ZSaberLv0** [comment]
正常现象, 旧版本 vim 不支持 `b:keymap_name`

另外, 这玩意儿是从 VimIM 搬过来的, vim 似乎也没有这个参数的相关说明和文档
