### ISSUE TITLE
可以再加入对韦大的[apc](https://github.com/skywind3000/vim-auto-popmenu)的切换支持

### ISSUE THREAD

**Issue by leoatchina** [ZSaberLv0/ZFVimIM#24]
可以再加入对韦大的[apc](https://github.com/skywind3000/vim-auto-popmenu)的切换支持，没测试但是我应该没有写错
```
function! s:apc_enable()
    if get(g:, 'ZFVimIM_autoDisable_apc', 1) && get(g:, 'apc_enable', 0) == 0
        ApcEnable
    endif
endfunction
function! s:apc_disable()
    if get(g:, 'ZFVimIM_autoDisable_apc', 1) && get(b:, 'apc_enable', 0) == 1
        ApcDisable
    endif
endfunction
call add(s:callback, ['s:apc_enable', 's:apc_disable'])
```

**Comment by ZSaberLv0** [comment]
测了下似乎不用加也不会冲突

**Comment by leoatchina** [comment]
我看了下，应该是这样的情况，对大写字母的处理zfvim和apc有冲突, 当然我这里还用了韦大的`vim-dict`
比如下面，在启用apc的情况下， 我想打一个`Z大`，结果一按`Z`直接把字典补全内容输入了
而且我按`C-w`回退删词，再按`Z`还是一样的情况
![image](https://user-images.githubusercontent.com/4470821/109404457-43da2f00-79a1-11eb-96bd-ed89366f699c.png)
`ApcDisable后正常`，所以我认为还是要处理下。

**Comment by leoatchina** [comment]
谢谢修改！
