### ISSUE TITLE
pinyin_huge.txt 被莫名删掉了很多词条

### ISSUE THREAD

**Issue by jdhao** [ZSaberLv0/ZFVimIM#25]
如题，[pinyin_huge.txt](https://github.com/ZSaberLv0/ZFVimIM_pinyin_huge/blob/master/misc/pinyin_huge.txt) 文件在使用中，不知道为啥被删掉了所有除 a 和 b 开头的词条，只剩下了正好 10000 行数据。目前还不清楚如何复现，可以确定是 插件的 bug，没有人工操作过这个文件。

**Comment by ZSaberLv0** [comment]
怀疑一个情况, 文件写入过程中, job 超时关闭或 vim 退出
我尝试先写临时文件看看

**Comment by ZSaberLv0** [comment]
bcd18a39f59a4722d1a370c9ad630c454761ab2f 优化了临时文件的处理方式, 试试看是否还会出现该问题?

**Comment by jdhao** [comment]
好，我更新一下，再观察能否复现问题。
