### ISSUE TITLE
关于补全列表里面的第二列的拼音显示

### ISSUE THREAD

**Issue by gVimer** [ZSaberLv0/ZFVimIM#29]
能不能把蓝色框里面的拼音显示去掉？
![微信截图_20210711102036](https://user-images.githubusercontent.com/6241431/125180865-bf8e9700-e231-11eb-895b-07a5a7746770.png)

**Comment by gVimer** [comment]
在打开或者关闭输入法的时候 VIM屏幕会闪一下 感觉是redraw了

**Comment by gVimer** [comment]
光标的颜色能设置成跟VIMIM那个插件的一样吗？淡绿色的

**Comment by ZSaberLv0** [comment]
1. 更新一下, 然后 `let g:ZFVimIM_showKeyHint = 0`
2. 不 `redraw` 某些玩意儿不会更新
3. 一样的, `:h hl-Pmenu` 系列

**Comment by gVimer** [comment]
多谢 那我先试试

**Comment by gVimer** [comment]
我先把redraw这个命令去掉了 这个闪一下太影响体验了
