### ISSUE TITLE
当世利器，无出其右，但是感觉可以给项目改个名字

### ISSUE THREAD

**Issue by hao-lee** [ZSaberLv0/ZFVimIM#3]
我在知乎看到的，第一反应是这个名字很奇怪，但是还是抱着试一试的心态测试了一把，心里只有一个字“叼”。完美的vimim继承者，比它还强，终于不用一个词一个词的敲了，此外，自动记忆词库实在是太方便了。

使用vim输入法的基本都听过vimim的名字，但这个项目加了个ZF前缀，使用者一眼看上去不知道是做什么的，我觉得vimim2或者vimim-plus之类的名字可能更有意义一些。:smirk:

**Comment by hao-lee** [comment]
该项目可以 @skywind3000 大神过来看一眼，我一直用gutentags_plus看代码，再用ZFVimIM写注释，生产效率大大的提高！

**Comment by ZSaberLv0** [comment]
名字什么的纯个人喜好，不是还有个谁啥都加deo么 :p

ZF代表Zero Framework，你会发现我折腾的轮子基本没有什么依赖，尽量最辣鸡的环境也能跑，有兴趣可以来试试 [ZF全家桶](https://github.com/ZSaberLv0?utf8=%E2%9C%93&tab=repositories&q=ZFVim)

**Comment by suliveevil** [comment]
减少依赖，这个理念我坚决支持！

**Comment by skywind3000** [comment]
不错啊
