### ISSUE TITLE
关闭词频修改和长语句输入

### ISSUE THREAD

**Issue by zeoxion** [ZSaberLv0/ZFVimIM#31]
先感谢大佬的插件, 很好用
1. 我想关闭词频修改, 最好能根据字典里的顺序固定顺序
2. 我想关闭长句输入, 因为我的字典这样输入可能不太方便, 会有冲突
3. 次选键能自定义吗

**Comment by zeoxion** [comment]
还有一个问题, 能有输入的提示吗, 就比如我字典中有
a 啊
aa 阿
aao 腌
等, 能在我输入a的时候提示aa, aao等字吗?

**Comment by ZSaberLv0** [comment]
更新一下, 然后:

1. 关闭词频修改和自造词

    ```
    let db = ZFVimIM_dbInit({
            \   'name' : 'pinyin',
            \   'editable' : '0',
            \ })
    ```

1. 关闭长句输入: `let g:ZFVimIM_sentence = 0`
1. 次选键是什么意思? 0~9 快捷选词的话目前没想到什么好方式替换, 翻页和快捷选词的话加了几个选项:

    ```
    let g:ZFVimIM_key_pageUp = ['-']
    let g:ZFVimIM_key_pageDown = ['=']
    let g:ZFVimIM_key_chooseL = ['[']
    let g:ZFVimIM_key_chooseR = [']']
    ```

1. a 和 aao 的问题, 更新一下试试? 之前全词匹配后就没有继续匹配预测词了

**Comment by lclrc** [comment]
> 次选键是什么意思?

他应该指的是二三候选字快捷键

比如: 现在前几个候选项是
1. 是
2. 时
3. 事
4. 使

假设有两个二三候选快捷键`;`和`'`, 那么:
`<space>`选择第一个候选"是", `;`选择第二个候选"时", `'`选择第三个候选"事"

**Comment by ZSaberLv0** [comment]
更新下, 然后试试这个?

```
let g:ZFVimIM_key_candidates=[';', "'"]
```

**Comment by lclrc** [comment]
👍 大佬太效率了, 好使! 这样如果词库合适的话基本不用数字去选字了
