### ISSUE TITLE
启动速度很慢,一开始,想禁用自动添加词库,不想词库被改动

### ISSUE THREAD

**Issue by Leiyi548** [ZSaberLv0/ZFVimIM#33]
作者你好,我是一名使用小鹤音形输入法的人,我在使用你这个插件出现几个问题一开始启动很慢,大约要10秒左右才能启动,我想要删除本地添加自己的词库.请问怎么才能实现,感谢你的贡献.

**Comment by ZSaberLv0** [comment]
启动慢问题, 参见: https://github.com/ZSaberLv0/ZFVimIM/issues/23#issuecomment-786664287

> https://github.com/ZSaberLv0/ZFVimIM#known-issue
> 请先确保:
> * executable('python') 或者 executable('python3')
> * ZFJobAvailable()
> 正常配置下, pinyin_huge 加载时间应该在 10 秒左右, 并且不会阻塞界面

---

自定义词库, 参考词库文件自己配置就行:

https://github.com/ZSaberLv0/ZFVimIM_pinyin_base/blob/master/misc/pinyin.txt
https://github.com/ZSaberLv0/ZFVimIM_pinyin_base/blob/master/plugin/ZFVimIM_pinyin.vim

**Comment by Leiyi548** [comment]
@ZSaberLv0 我是想要把那个自动添加词库这个功能关掉..

**Comment by Leiyi548** [comment]
@ZSaberLv0 我那个python和zfjobavailbale正常.

**Comment by ZSaberLv0** [comment]
> 我是想要把那个自动添加词库这个功能关掉..

```
let db = ZFVimIM_dbInit({
            \   'name' : 'pinyin',
            \   'editable' : 0,         <== 禁止编辑
            \ })
```

---

> 我那个python和zfjobavailbale正常.

参考 https://github.com/ZSaberLv0/ZFVimIM/issues/23#issuecomment-786725597 提供一下日志

**Comment by Leiyi548** [comment]
@ZSaberLv0  我用了你给我的最小的mini.vim进行测试,但是当我要运行 call writefile(g:ZFJobVerboseLog, 'log.txt')
![image](https://user-images.githubusercontent.com/76139422/139460967-acca9315-c996-4261-b65a-11cf8fd71f43.png)
我只能提供第一个出来的图片
![image](https://user-images.githubusercontent.com/76139422/139461020-4d64822f-0138-4358-931f-585a91fdc0bc.png)
我用了min.vim加载zfvim依然启动要10秒...

**Comment by ZSaberLv0** [comment]
`call ZFVimIM_DEBUG_checkHealth()` 看看？

dbLoad 这么费时肯定是 python 或 job 不支持，然后跑纯 vim 脚本的词库加载了

**Comment by Leiyi548** [comment]
@ZSaberLv0 
![image](https://user-images.githubusercontent.com/76139422/139518550-f82e8a5f-6239-4b67-9aaa-6a5546ddbaaa.png)
我这个job显示0但是nvim又显示1

**Comment by Leiyi548** [comment]
@ZSaberLv0 我这里有两个python是这个的影响吗?

**Comment by ZSaberLv0** [comment]
https://github.com/ZSaberLv0/ZFVimJob/blob/master/plugin/api_impl_nvim.vim
`:source` 这个文件看看有没有报错?
然后再看看 `:echo g:ZFVimJobImpl` 是个啥

**Comment by Leiyi548** [comment]
@ZSaberLv0 是要source插件目录下这个文件吗?

**Comment by Leiyi548** [comment]
@ZSaberLv0  我发现我刚刚之所以加载慢是因为我PlugInstall没有下载zfvimjob
当我下载了zfvimjob我发现加载就很快了,基本在1s完成.我去测试下我的原来配置看下,
再问下如何关闭这个状态栏显示
![image](https://user-images.githubusercontent.com/76139422/139520014-b1d2df5f-9604-4ee3-840e-4b6531a44b0a.png)

**Comment by Leiyi548** [comment]
@ZSaberLv0 我发现我之前之所以会加载很慢是因为我lazyload了zfvim和zfvimjob,我发现这个不能lazyload
我用packer.nvim来管理插件,当我lazyload他们在insert之后加载我发现他就无法调用zfvimjob来加快zfvimim这个插件.

**Comment by ZSaberLv0** [comment]
状态栏的内容是 vim 的 `lmap` 显示的，只能改文本，似乎无法隐藏

**Comment by Leiyi548** [comment]
@ZSaberLv0 谢谢你的帮助,我已经解决了问题,可以关闭这个问题了.感谢你的帮助.

**Comment by Leiyi548** [comment]
@ZSaberLv0  
![image](https://user-images.githubusercontent.com/76139422/139523394-4ac641ac-754c-4f3c-ae11-c629ffb0cfcc.png)
请问wo我每次打开vim都会加载这句话是啥,这是我下载别人的词库

**Comment by ZSaberLv0** [comment]
字面意思，加载成功
