### ISSUE TITLE
如何去掉词库更新(加载)提醒,会吧状态栏给搞没

### ISSUE THREAD

**Issue by Leiyi548** [ZSaberLv0/ZFVimIM#34]
![image](https://user-images.githubusercontent.com/76139422/139870933-2ec6967b-e9e2-4477-b25c-3fb9460644d3.png)

**Comment by ZSaberLv0** [comment]
```
let g:ZFVimIM_cloudAsync_outputTo = {}
```

**Comment by Leiyi548** [comment]
@ZSaberLv0 谢谢
