### ISSUE TITLE
输入法似乎会干扰vim的搜索操作

### ISSUE THREAD

**Issue by hao-lee** [ZSaberLv0/ZFVimIM#4]
首先插入模式下`;;`开启输入法，然后回到普通模式，然后按`/`搜搜字符串时，我按下的字母都不显示，除非我在此时再按`;;`把输入法关掉。请问，这是期望的行为吗？

**Comment by ZSaberLv0** [comment]
没有 python 和 job 的时候, 首次启用会同步的加载词库, 词库比较大的话会阻塞比较久, 先确认下是不是这个问题 (比如是否第二次切换的时候就正常了)

如果还是不行的话, 麻烦提供一下以下信息:

* `:version`
* `:echo has('timers')`
* `:echo has('python') || has('python3')`
* `:echo ZFVimIM_cloudAsyncAvailable()`
* `:messages`

**Comment by hao-lee** [comment]
```
版本为 8.2
timers 为 1
python3 支持
echo ZFVimIM_cloudAsyncAvailable() 是 1
messages 除了显示vim作者之外没有其他信息
```

我录了个gif(压缩了一下，好像不会循环播放了，刷新页面可以从头看)，老铁看下问题现象，我的操作也没有什么很神奇的地方。好奇怪。
![2020-05-17-19-42-28](https://user-images.githubusercontent.com/8112645/82143563-6d452680-9877-11ea-80bd-97b9ef268179.gif)

打开文件，输入一行字，然后`;;`进入拼音模式，然后回到普通模式想搜一下`this`就出现了图中现象，之后尝试删除操作，会发现莫名其妙出来了一串字符像是个函数名。我猜测是`ZFVimIME_callOmni()`函数打印出来的。

**Comment by hao-lee** [comment]
此外，我还触发过另一个问题，就是我不知道怎么回事在拼音模式下触发了C语言的omni补全，然后输入法和omni好像在竞争我的按键，输入法就不起作用了，打不出字，这个我还没找到复现步骤。

**Comment by ZSaberLv0** [comment]
之前没注意, `lmap` 在 command line 也会生效, 现在应该可以了 (大概 - -b)

**Comment by hao-lee** [comment]
666，碉堡了，非常感谢，辛苦了！
