### ISSUE TITLE
请问可否设置从n个字母后开始匹配?

### ISSUE THREAD

**Issue by sakcer** [ZSaberLv0/ZFVimIM#44]
例如输入两个字母后开始弹窗

**Comment by ZSaberLv0** [comment]
更新一下, 然后添加以下配置:

``` vim
function! ZFVimIM_complete(key, ...)
    if len(a:key) >= 2
        return ZFVimIM_completeDefault(a:key, get(a:, 1, {}))
    else
        return []
    endif
endfunction
```

**Comment by sakcer** [comment]
> 更新一下, 然后添加以下配置:
> 
> ```viml
> function! ZFVimIM_complete(key, ...)
>     if len(a:key) >= 2
>         return ZFVimIM_completeDefault(a:key, get(a:, 1, {}))
>     else
>         return []
>     endif
> endfunction
> ```

好用，太感谢了！！！！

**Comment by sakcer** [comment]
请问可以把部分弹框的内容关闭吗? 如果可以需要怎么设置?
还有是否可以将选词框横向显示?

**Comment by ZSaberLv0** [comment]
> 请问可以把部分弹框的内容关闭吗? 如果可以需要怎么设置?
* 右下角 job 提示: `let g:ZFJobIndicator = 0`
* statusline 提示: `let g:ZFVimIM_cloudAsync_outputTo = {}`

---

> 还有是否可以将选词框横向显示?
* 不行, 这玩意儿是 vim 的 `:h ins-completion-menu`

**Comment by sakcer** [comment]
好的, 我试试
感谢
