### ISSUE TITLE
输入法打开的情况下，从normal模式下按`i`或`a`进入到插入模式的过程会卡将近1秒钟

### ISSUE THREAD

**Issue by persytry** [ZSaberLv0/ZFVimIM#45]
输入法打开的情况下，从normal模式下按`i`或`a`进入到插入模式的过程会卡将近1秒钟，就是说当我按了`i`键以后，才会进入到插入模式。
不知道会不会跟最新版的nvim有关，我的nvim版本：
![image](https://user-images.githubusercontent.com/88146305/168022360-500c1498-d1ca-45e9-aeb0-6da1dffd042d.png)

**Comment by ZSaberLv0** [comment]
1. `call ZFVimIM_DEBUG_checkHealth()` 看看输出啥
2. `let g:ZFVimIM_DEBUG_profile = 1` 然后操作一下, 再 `call ZFVimIM_DEBUG_profileInfo()` 看看输出啥

**Comment by persytry** [comment]
输出的是这个
![image](https://user-images.githubusercontent.com/88146305/168025556-a296ae5b-f4c0-4ffb-b300-60261d5894eb.png)

**Comment by ZSaberLv0** [comment]
1. 装一下这个插件: https://github.com/ZSaberLv0/ZFVimUtil
2. `:ZFProfileStart`
3. 复现一下问题, 然后退出 vim 并重新打开, 应该会自动打开个日志文件, 把末尾的两项贴上来看看 (`FUNCTIONS SORTED ON xxx TIME`)

**Comment by persytry** [comment]
我现在用的是wsl打开的nvim，当我把窗口切出再切回来的时候（比如从nvim切出到chrome浏览器，然后再切回到nvim窗口），第一次按`i`键，反应很迅速，是正常的。然后我再从insert模式切换到normal模式，再按`i`就会卡1秒。 也就是说，只要不切出nvim到其他系统窗口，第一次按`i`是正常的，之后全都不正常，都会卡

**Comment by persytry** [comment]
你说的那个插件装上了，但是重启后就又没问题了，我还没找到复现的办法，等再出现问题后，再来请教。
