### ISSUE TITLE
在VIM9.0版本上好像失效了

### ISSUE THREAD

**Issue by gVimer** [ZSaberLv0/ZFVimIM#47]
用了最近发布的[gVim9.0](https://github.com/vim/vim-win32-installer/releases) 然后输入法好像不能输入了 麻烦有空看下

**Comment by ZSaberLv0** [comment]
具体什么问题? [gVim9.0](https://github.com/vim/vim-win32-installer/releases) 测试正常可用

**Comment by gVimer** [comment]
好像是映射的问题
`nnoremap <expr><silent> <C-_> ZFVimIME_keymap_toggle_n()`
`inoremap <expr><silent> <C-_> ZFVimIME_keymap_toggle_i()`
之前是可用的 但是这个9.0版本不知道为啥用不了了

**Comment by ZSaberLv0** [comment]
映射问题非本插件问题

`<c-i>` 之类的特殊键没法用于按键映射, 估计 vim9 新增了 `<c-_>` 的什么特殊用途, `:h i_CTRL-_`

**Comment by gVimer** [comment]
好的 不好意思 打扰了
