### ISSUE TITLE
在输入的时候命令行出会闪烁和弹出菜单的闪烁

### ISSUE THREAD

**Issue by gVimer** [ZSaberLv0/ZFVimIM#48]
如图
![LbySwlVnmt](https://user-images.githubusercontent.com/6241431/177756234-39448fbe-6234-4c25-bf6f-53332fc6c108.gif)
就是这个函数调用的时候 能去掉么 或者加上**silent**
![Dingtalk_20220707184410](https://user-images.githubusercontent.com/6241431/177756256-a535911e-f833-4c11-9696-2e2dfac1b4e9.jpg)

**Comment by ZSaberLv0** [comment]
这玩意儿是用 `i_CTRL-R` + `feedkeys` 触发的, 目前是没发现有什么方式能绕过这个闪烁问题

**Comment by gVimer** [comment]
好的 那先就这样吧

**Comment by gVimer** [comment]
![gVim_z71ndgF6re](https://user-images.githubusercontent.com/6241431/178209902-e156afa0-06f9-434a-85b9-bd91fc4d7ef4.gif)
这个弹出菜单在输入的时候经常闪屏能优化吗？

**Comment by ZSaberLv0** [comment]
似乎没有什么好方法, 太长的输入会引起词库匹配耗时明显增加, 而词库匹配这种不太适合做缓存及异步, 毕竟本插件主要目的之一还包括兼容纯 vim script 环境

另外, 这种闪屏现象只在 Windows 非常明显, 其他平台即使耗时卡顿也不会造成闪屏, 原因不明

**Comment by gVimer** [comment]
好的 谢了! 太长输入只是为了说明闪屏的问题  实际输入中不会这样 刚在Mac上试了确实不会这样闪 应该是GVIM本身的问题了
