### ISSUE TITLE
隐藏命令行的函数显示

### ISSUE THREAD

**Issue by BLACKSWORD0** [ZSaberLv0/ZFVimIM#50]
您好，很感谢您做了这个插件，这个解决了很多地方不支持输入法的问题。但是我还是遇到了一点使用层面的问题。
我想在neovide中使用这个插件，因为neovide使用中文输入法似乎有些问题，因此我想借助于这个插件。 但是在使用这个插件时会出现下面这种问题

https://user-images.githubusercontent.com/56479341/226635498-dddc7978-993f-46bd-a8b5-c63eb4b04575.mp4

neovide有一个比较好看的点是可以让光标在前后所在的位置跳动，但是因为使用这个插件时总会在命令行显示那个函数名称，导致光标一直长距离来回跳动，请问是否可以彻底隐藏中途使用时命令行的信息呢？

**Comment by ZSaberLv0** [comment]
`silent` 好像能解决部分问题, 不过 ZFVimIM_openapi 这种异步刷界面的似乎依然没法避免
简单试了试其他补全框架似乎也有这个现象

**Comment by BLACKSWORD0** [comment]
哦哦，好的，我升级了，确实减少了一部分的跳动。

**Comment by BLACKSWORD0** [comment]
那现在我是否要关闭这个issue呢
