### ISSUE TITLE
Status Flick between Command/Insert mode

### ISSUE THREAD

**Issue by hiberabyss** [ZSaberLv0/ZFVimIM#53]
When input some chars, the screen will keep flicking:

![iShot_2023-04-07_19 33 19](https://user-images.githubusercontent.com/2898670/230602264-09048c97-6cfa-4395-8b63-b525a9e2ac50.gif)

**Comment by hiberabyss** [comment]
Use NVIM v0.8.3

**Comment by hiberabyss** [comment]
Currently only the `bcgl` characters will trigger the problem. A little strange.

**Comment by ZSaberLv0** [comment]
please supply a minimal config and reproduce steps
seems conflict with other plugins or keymaps
