### ISSUE TITLE
如果在输入的时候按ESC键会删除一整行

### ISSUE THREAD

**Issue by qx220** [ZSaberLv0/ZFVimIM#59]
https://github.com/user-attachments/assets/1d0aebbb-c755-4183-8c9e-eb591c9178cd

参考视频，有些时候输入到一半想取消操作按ESC,会把当前一行已经输入的内容也删除掉

**Comment by ZSaberLv0** [comment]
```
filetype plugin indent on
syntax on
set nocompatible
let g:plug_home = $HOME . '/.vim/bundle'
let g:plug_url_format = 'https://github.com/%s'
execute 'source ' . g:plug_home . '/vim-plug/plug.vim'
silent! call plug#begin()
Plug 'junegunn/vim-plug'
Plug 'ZSaberLv0/ZFVimIM'
Plug 'ZSaberLv0/ZFVimIM_pinyin'
Plug 'ZSaberLv0/ZFVimJob'
call plug#end()
```

1. 试试最简配置是否正常
1. 提供一下:
    * `:version`
    * `:echo exists('v:completed_item')`
    * `:echo exists('##CompleteDone')`
    * `:echo ZFVimIM_json_available()`
    * `:call ZFVimIM_DEBUG_checkHealth()`
