### ISSUE TITLE
当前最新代码 30e96cc 似乎又引入了问题

### ISSUE THREAD

**Issue by hao-lee** [ZSaberLv0/ZFVimIM#6]
在插入模式下启用输入法后，回到普通模式，按下 `/` 想搜索字符串，结果输入的字符不显示

**Comment by ZSaberLv0** [comment]
更新下试试? 我也不知道为啥只用 `redraw` 就不会刷新

**Comment by hao-lee** [comment]
这次倒是能搜索了，但是...候选词下拉框一闪就没，只在按键的瞬间有下拉框出现，没机会敲空格上屏...

**Comment by hao-lee** [comment]
而且 30e96cc 这个版本抛开搜索不显示的问题，输入的感觉的也很卡，反应比较慢...老铁，是不是重构崩了...

**Comment by ZSaberLv0** [comment]
应该也许大概可以了 - -b

**Comment by hao-lee** [comment]
用起来可以了，应该没问题了 😄
