### ISSUE TITLE
如何避免command window echo

### ISSUE THREAD

**Issue by qx220** [ZSaberLv0/ZFVimIM#60]
![Screenshot from 2024-08-15 17-56-47](https://github.com/user-attachments/assets/324b3493-ff40-4ce8-9640-98ac31ff54a2)
如图所示，每次在输入的时候左下角的command window都会echo插件调用的函数，有什么办法避免显示这个echo吗？

**Comment by ZSaberLv0** [comment]
这玩意儿依赖于 `<c-r>=` 在输入过程中调用函数, 补全函数涉及较长时间的词库搜索, 除了像 LSP 那样搞复杂的异步补全框架外, 目前没发现有什么解决方案

**Comment by qx220** [comment]
建了一个pr #61 ，这种极简的方案（直接echo ''来重置）不知道会不会有副作用

**Comment by ZSaberLv0** [comment]
副作用应该是没有, 但是确定有效果吗? 按原理来看应该是没有什么区别才对

**Comment by qx220** [comment]
https://github.com/user-attachments/assets/029e7655-78c6-4a4a-8bea-dd7be646b0c7

在我的机子上（vim9.1）是有效果的

**Comment by ZSaberLv0** [comment]
合并了
