### ISSUE TITLE
输入法和插入模式的切换会导致报错

### ISSUE THREAD

**Issue by hao-lee** [ZSaberLv0/ZFVimIM#7]
我有时候在输入法模式下想临时输入几个单词，又不想切回英文模式，于是会在输入单词后后直接敲回车让英文上屏，不知道这种操作在不在设计范围内...这种行为当时没问题，但是后期再切英文模式就会触发一个 `bug`，复现步骤如下：

1. `vim` 打开，进入 `insert mode`，然后 `;;` 切到输入法
2. 输入几个字母比如 `yingwen`，直接敲回车让英文上屏
3. `;;` 切回 `insert mode`
4. 再输入任意字母键比如 `c`，报错就出现了

```
=ZFVimIME_input()
E764: Option 'omnifunc' is not set
Press ENTER or type command to continue
```

要想让这个问题不出现的话，第三步要再加一次 `;;` 才行，也就是说当我连续使用两次 `;;`，vim 状态栏显示的模式虽然都是 `-- INSERT --`，但第一次是假的，第二次才是真的。如果只使用一次 `;;` 在假的 `-- INSERT --` 下输入就会报错。

这个问题出现之后如果不重启 vim，之后输入法切 `insert` 或 `insert` 切输入法都要使出两次 `;;`。

**Comment by ZSaberLv0** [comment]
更新下试试?

`i_CTRL-^` 真是太操蛋了, 各种麻烦事

**Comment by hao-lee** [comment]
可以了，稳如狗，这次我感觉应该稳定了 😏
