### ISSUE TITLE
有没办法输入中文全角符号？

### ISSUE THREAD

**Issue by deaniiyu** [ZSaberLv0/ZFVimIM#8]
好像输入的符号都是英文的？目前我是直接把全角符号存到字典里来输入，能用是能用就是别扭了点。
不管怎么说，应该是目前vim上最好的输入法，性能完爆vimim，即便arm设备也没延迟。
再见iPad pro。matepad pro + termux + texlive + vimtex，起飞就完事了。

**Comment by ZSaberLv0** [comment]
emmm... 倒是有办法实现, 不过比较麻烦, 有空的时候考虑下

**Comment by ZSaberLv0** [comment]
@deaniiyu 试试 `g:ZFVimIM_symbolMap`

**Comment by hao-lee** [comment]
卧槽，作者是我见过回应issue最快的开发者，老哥白天晚上都这么效率，啥工作啊

**Comment by deaniiyu** [comment]
> @deaniiyu 试试 `g:ZFVimIM_symbolMap`

搞定，老哥牛逼。

**Comment by ZSaberLv0** [comment]
不小心把测试的配置上传了, 更新一下, 然后自己添加 `g:ZFVimIM_symbolMap`

个人感觉默认还是不要启用字符转换比较好
